### PR TITLE
fix the reviews

### PR DESCRIPTION
**Pull request by IronConrad**
add photos and fix the text

### CODE REVIEW

**Comment by IronConrad** [comment]
add photos and fix the text

**Review by IronConrad — COMMENTED** [review]
add photos

**Review by IronConrad — COMMENTED** [review]
add 4 photos

**Review by IronConrad — COMMENTED** [review]
pdf

**Comment by lijiarui** [comment]
duplicate with  https://github.com/wechaty/bot5.ml/pull/227

**Pull request closed without merging**
